<?php
namespace Modules\Attraction\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\Booking\Models\Booking;
use Modules\FrontendController;
use Modules\Attraction\Models\Attraction;
use Modules\Attraction\Models\AttractionDate;

class AvailabilityController extends FrontendController{

    protected $attractionClass;
    /**
     * @var AttractionDate
     */
    protected $attractionDateClass;
    /**
     * @var Booking
     */
    protected $bookingClass;

    protected $indexView = 'Attraction::frontend.user.availability';

    public function __construct()
    {
        parent::__construct();
        $this->attractionClass = Attraction::class;
        $this->attractionDateClass = AttractionDate::class;
        $this->bookingClass = Booking::class;
    }
    public function callAction($method, $parameters)
    {
        if(setting_item('attraction_disable'))
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index(Request $request){
        $this->checkPermission('tour_create');

        $q = $this->attractionClass::query();

        if($request->query('s')){
            $q->where('title','like','%'.$request->query('s').'%');
        }

        if(!$this->hasPermission('tour_manage_others')){
            $q->where('create_user',$this->currentUser()->id);
        }

        $q->orderBy('bravo_attractions.id','desc');

        $rows = $q->paginate(15);

        $current_month = strtotime(date('Y-m-01',time()));

        if($request->query('month')){
            $date = date_create_from_format('m-Y',$request->query('month'));
            if(!$date){
                $current_month = time();
            }else{
                $current_month = $date->getTimestamp();
            }
        }
        $breadcrumbs = [
            [
                'name' => __('Attractions'),
                'url'  => route('attraction.vendor.index')
            ],
            [
                'name'  => __('Availability'),
                'class' => 'active'
            ],
        ];
        $page_title = __('Attractions Availability');

        return view($this->indexView,compact('rows','breadcrumbs','current_month','page_title','request'));
    }

    public function loadDates(Request $request){

        $request->validate([
            'id'=>'required',
            'start'=>'required',
            'end'=>'required',
        ]);

        $attraction = $this->attractionClass::find($request->query('id'));
        if(empty($attraction)){
            $this->sendError(__('Attraction not found'));
        }
	    $is_single = $request->query('for_single');

        $query = $this->attractionDateClass::query();
        $query->where('target_id',$request->query('id'));
        $query->where('start_date','>=',date('Y-m-d H:i:s',strtotime($request->query('start'))));
        $query->where('end_date','<=',date('Y-m-d H:i:s',strtotime($request->query('end'))));
        $rows =  $query->take(40)->get();
        $allDates = [];
        for($i = strtotime($request->query('start')); $i <= strtotime($request->query('end')); $i+= DAY_IN_SECONDS)
        {
            $date = [
                'id'=>rand(0,999),
                'active'=>0,
                'price'=>(!empty($attraction->sale_price) and $attraction->sale_price > 0 and $attraction->sale_price < $attraction->price) ? $attraction->sale_price : $attraction->price,
                'is_default'=>true,
                'textColor'=>'#2791fe'
            ];

	        if(!$is_single){
		        $date['price_html'] = format_money_main($date['price']);
	        }else{
		        $date['price_html'] = format_money($date['price']);

	        }

            $date['max_guests'] = $attraction->max_people;
            $date['title'] = $date['event']  = $date['price_html'];
            $date['start'] = $date['end'] = date('Y-m-d',$i);
            if($attraction->default_state){
                $date['active'] = 1;
            }else{
                $date['title'] = $date['event'] = __('Blocked');
                $date['backgroundColor'] = 'orange';
                $date['borderColor'] = '#fe2727';
                $date['classNames'] = ['blocked-event'];
                $date['textColor'] = '#fe2727';
            }

            if($request->input('for_single')){
                if(empty(!$attraction->max_people) and $attraction->max_people < 1){
                    $date['active'] = 0;
                }
            }

            if(!empty($attraction->meta->enable_person_types) and $attraction->meta->enable_person_types==1){
                $date['person_types'] = $attraction->meta->person_types ;
                if(!empty( $date['person_types'] )){
                    $c_title = "";
                    foreach (  $date['person_types']  as &$person){

                        if(!$is_single){
	                        $c_title .= $person['name'].": ".format_money_main($person['price'])."<br>";
	                        //for single
	                        $person['display_price'] = format_money_main($person['price']);
                        }else{
	                        $c_title .= $person['name'].": ".format_money($person['price'])."<br>";
	                        //for single
	                        $person['display_price'] = format_money($person['price']);
                        }
                        $person['number'] = $person['min'] ?? 0;
                    }
                    $date['title'] = $date['event']  = $c_title;
                }
            }

            // Open Hours
            if (!empty($attraction->meta->enable_open_hours) and $attraction->meta->enable_open_hours == 1) {
                $open_hours = $attraction->meta->open_hours;
                $nDate = date('N', $i);
                if (!isset($open_hours[$nDate]) or empty($open_hours[$nDate]['enable'])) {
                    $date['active'] = 0;
                }
            }

            $allDates[date('Y-m-d',$i)] = $date;
        }
        if(!empty($rows))
        {
            foreach ($rows as $row)
            {
                $row->start = date('Y-m-d',strtotime($row->start_date));
                $row->end = date('Y-m-d',strtotime($row->start_date));
                $row->textColor = '#2791fe';

                $price = $row->price;
                if(empty($price)){
                    $price = (!empty($attraction->sale_price) and $attraction->sale_price > 0 and $attraction->sale_price < $attraction->price) ? $attraction->sale_price : $attraction->price;
                }

	            if(!$is_single){
		            $row->title = $row->event = format_money_main($price);
	            }else{
		            $row->title = $row->event = format_money($price);

	            }

                $row->price = $price;

                if($request->input('for_single')){
                    if(empty(!$row->max_guests) and $row->max_guests < 1 ){
                        $row->active = 0;
                    }
                }
                $list_person_types = null;
                if(!empty($attraction->meta->enable_person_types) and $attraction->meta->enable_person_types==1){
                    $list_person_types = is_array($row->person_types) ? $row->person_types : $attraction->meta->person_types;
                    if(!empty($list_person_types) and is_array($list_person_types)){
                        $c_title = "";
                        foreach ($list_person_types as &$person){

	                        if(!$is_single){
		                        $c_title .= $person['name'].": ".format_money_main($person['price'])."<br>";
		                        //for single
		                        $person['display_price'] = format_money_main($person['price']);
	                        }else{
		                        $c_title .= $person['name'].": ".format_money($person['price'])."<br>";
		                        //for single
		                        $person['display_price'] = format_money($person['price']);
	                        }

                            $person['number'] = $person['min'] ?? 0;
                        }
                        $row->title  = $c_title;
                    }
                }
                $row->person_types = $list_person_types;

                if(!$row->active)
                {
                    $row->title = $row->event = __('Blocked');
                    $row->backgroundColor = '#fe2727';
                    $row->classNames = ['blocked-event'];
                    $row->textColor = '#fe2727';
                    $row->active = 0;
                }else{
                    $row->classNames = ['active-event'];
                    $row->active = 1;
                    // Open Hours
                    if (!empty($attraction->meta->enable_open_hours) and $attraction->meta->enable_open_hours == 1) {
                        $open_hours = $attraction->meta->open_hours;
                        $nDate = date('N', strtotime($row->start_date));
                        if (!isset($open_hours[$nDate]) or empty($open_hours[$nDate]['enable'])) {
                            $row->active = 0;
                        }
                    }

                }
                $allDates[date('Y-m-d',strtotime($row->start_date))] = $row->toArray();
            }
        }

        $bookings = $this->bookingClass::getBookingInRanges($attraction->id,$attraction->type,$request->query('start'),$request->query('end'));
        if(!empty($bookings))
        {
            foreach ($bookings as $booking){
                for($i = strtotime($booking->start_date); $i <= strtotime($booking->end_date); $i+= DAY_IN_SECONDS){
                    if(isset($allDates[date('Y-m-d',$i)])){
                        $total_guests_booking = $booking->total_guests;
                        $max_guests = $allDates[date('Y-m-d',$i)]['max_guests'];
                        if($total_guests_booking >= $max_guests){
                            $allDates[date('Y-m-d',$i)]['active'] = 0;
                            $allDates[date('Y-m-d',$i)]['event'] = __('Full Book');
                            $allDates[date('Y-m-d',$i)]['title'] = __('Full Book');
                            $allDates[date('Y-m-d',$i)]['classNames'] = ['full-book-event'];
                        }
                    }
                }
            }
        }

        $data = array_values($allDates);

        return response()->json($data);
    }

    public function store(Request $request){

        $request->validate([
            'target_id'=>'required',
            'start_date'=>'required',
            'end_date'=>'required'
        ]);

        $attraction = $this->attractionClass::find($request->input('target_id'));
        $target_id = $request->input('target_id');

        if(empty($attraction)){
            $this->sendError(__('Attraction not found'));
        }

        if(!$this->hasPermission('tour_manage_others')){
            if($attraction->create_user != Auth::id()){
                $this->sendError("You do not have permission to access it");
            }
        }

        $postData = $request->input();
        if(!empty($person_types = $postData['person_types']) and is_array($person_types)){
            foreach ($person_types as &$item){
                $item['display_price'] = format_money($item['price']);
            }
            $postData['person_types'] = $person_types;
        }else{
            $postData['person_types'] = null;
        }

        for($i = strtotime($request->input('start_date')); $i <= strtotime($request->input('end_date')); $i+= DAY_IN_SECONDS)
        {
            $date = $this->attractionDateClass::where('start_date',date('Y-m-d',$i))->where('target_id',$target_id)->first();
            if(empty($date)){
                $date = new $this->attractionDateClass();
                $date->target_id = $target_id;
            }
            $postData['start_date'] = date('Y-m-d H:i:s',$i);
            $postData['end_date'] = date('Y-m-d H:i:s',$i);
            $date->fillByAttr([
                'start_date','end_date','price',
                'max_guests',
                'active',
                'person_types'
            ],$postData);
            $date->save();
        }
        $this->sendSuccess([],__("Update Success"));
    }
}
