<?php
namespace Modules\Attraction\Controllers;

use Modules\FrontendController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\Attraction\Models\Attraction;
use Modules\Attraction\Models\AttractionCategory;
use Modules\Attraction\Models\AttractionTranslation;
use Modules\Location\Models\Location;
use Modules\Core\Models\Attributes;
use Modules\Attraction\Models\AttractionTerm;
use Modules\Booking\Models\Booking;

class ManageAttractionController extends FrontendController
{
    protected $attractionClass;
    protected $attractionTranslationClass;
    protected $attractionCategoryClass;
    protected $attractionTermClass;
    protected $attributesClass;
    protected $locationClass;
    protected $bookingClass;

    public function __construct()
    {
        $this->attractionClass = Attraction::class;
        $this->attractionTranslationClass = AttractionTranslation::class;
        $this->attractionCategoryClass = AttractionCategory::class;
        $this->attractionTermClass = AttractionTerm::class;
        $this->attributesClass = Attributes::class;
        $this->locationClass = Location::class;
        $this->bookingClass = Booking::class;

        parent::__construct();
    }

    public function callAction($method, $parameters)
    {
        if(setting_item('attraction_disable'))
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function manageAttraction(Request $request)
    {
        $this->checkPermission('tour_view');
        $user_id = Auth::id();
        $list_attraction = $this->attractionClass::where("create_user", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows' => $list_attraction->paginate(5),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Attractions'),
                    'url'   => route('attraction.vendor.index'),
                ],
                [
                    'name'  => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Manage Attractions"),
        ];
        return view('Attraction::frontend.manageAttraction.index', $data);
    }

    public function createAttraction(Request $request)
    {
        $this->checkPermission('tour_create');
        $row = new $this->attractionClass();
        $data = [
            'row'           => $row,
            'translation' => new $this->attractionTranslationClass(),
            'attraction_category' => $this->attractionCategoryClass::get()->toTree(),
            'attraction_location' => $this->locationClass ::get()->toTree(),
            'attributes'    => $this->attributesClass::where('service', 'attraction')->get(),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Attractions'),
                    'url'   => route('attraction.vendor.index'),
                ],
                [
                    'name'  => __('Create'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Create Attractions"),
        ];
        return view('Attraction::frontend.manageAttraction.detail', $data);
    }

    public function editAttraction(Request $request, $id)
    {
        $this->checkPermission('tour_update');
        $user_id = Auth::id();
        $row = $this->attractionClass::where("create_user", $user_id);
        $row = $row->find($id);
        if (empty($row)) {
            return redirect(route('attraction.vendor.index'))->with('warning', __('Attraction not found!'));
        }
        $translation = $row->translateOrOrigin($request->query('lang'));
        $data = [
            'translation'    => $translation,
            'row'           => $row,
            'attraction_category' => $this->attractionCategoryClass::get()->toTree(),
            'attraction_location' => $this->locationClass::get()->toTree(),
            'attributes'    => $this->attributesClass::where('service', 'attraction')->get(),
            "selected_terms" =>  $row->attraction_term->pluck('term_id'),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Attractions'),
                    'url'   => route('attraction.vendor.index'),
                ],
                [
                    'name'  => __('Edit'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Edit Attractions"),
        ];
        return view('Attraction::frontend.manageAttraction.detail', $data);
    }

    public function store( Request $request, $id ){
        if($id>0){
            $this->checkPermission('tour_update');
            $row = $this->attractionClass::find($id);
            if (empty($row)) {
                return redirect(route('attraction.vendor.edit',['id'=>$row->id]));
            }

            if($row->create_user != Auth::id() and !$this->hasPermission('tour_manage_others'))
            {
                return redirect(route('attraction.vendor.edit',['id'=>$row->id]));
            }

        }else{
            $this->checkPermission('tour_create');
            $row = new $this->attractionClass();
            $row->status = "publish";
            if(setting_item("attraction_vendor_create_service_must_approved_by_admin", 0)){
                $row->status = "pending";
            }
        }

        $row->fillByAttr([
            'title',
            'content',
            'image_id',
            'banner_image_id',
            'short_desc',
            'category_id',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'gallery',
            'video',
            'default_state',
            'price',
            'sale_price',
            'duration',
            'max_people',
            'min_people',
            'faqs',
            'include',
            'exclude',
            'tc',
            'itinerary',
        ], $request->input());

        $res = $row->saveOriginOrTranslation($request->input('lang'),true);
        if ($res) {
            if(!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
            }
            $row->saveMeta($request);
            if($id > 0 ){
                return back()->with('success',  __('Attraction updated') );
            }else{
                return redirect(route('attraction.vendor.edit',['id'=>$row->id]))->with('success', __('Attraction created') );
            }
        }
    }

    public function saveTerms($row, $request)
    {
        if (empty($request->input('terms'))) {
            $this->attractionTermClass::where('attraction_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->attractionTermClass::firstOrCreate([
                    'term_id' => $term_id,
                    'attraction_id' => $row->id
                ]);
            }
            $this->attractionTermClass::where('attraction_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }

    public function deleteAttraction($id)
    {
        $this->checkPermission('attraction_delete');
        $user_id = Auth::id();
        $query = $this->attractionClass::where("create_user", $user_id)->where("id", $id)->first();
        if(!empty($query)){
            $query->delete();
        }
        return redirect(route('attraction.vendor.index'))->with('success', __('Delete attraction success!'));
    }

    public function bulkEditAttraction($id , Request $request){
        $this->checkPermission('tour_update');
        $action = $request->input('action');
        $user_id = Auth::id();
        $query = $this->attractionClass::where("create_user", $user_id)->where("id", $id)->first();
        if (empty($id)) {
            return redirect()->back()->with('error', __('No item!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        if(empty($query)){
            return redirect()->back()->with('error', __('Not Found'));
        }
        switch ($action){
            case "make-hide":
                $query->status = "draft";
                break;
            case "make-publish":
                $query->status = "publish";
                break;
        }
        $query->save();
        return redirect()->back()->with('success', __('Update success!'));
    }

    public function bookingReport(Request $request)
    {
        $data = [
            'bookings' => $this->bookingClass::getBookingHistory($request->input('status'), false ,Auth::id() , 'attraction'),
            'statues'  => config('booking.statuses'),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Attractions'),
                    'url'   => route('attraction.vendor.index'),
                ],
                [
                    'name'  => __('Booking Report'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Booking Report"),
        ];
        return view('Attraction::frontend.manageAttraction.bookingReport', $data);
    }

    public function bookingReportBulkEdit($booking_id , Request $request){
        $status = $request->input('status');
        if (!empty(setting_item("attraction_allow_vendor_can_change_their_booking_status")) and !empty($status) and !empty($booking_id)) {
            $query = $this->bookingClass::where("id", $booking_id);
            $query->where("vendor_id", Auth::id());
            $item = $query->first();
            if(!empty($item)){
                $item->status = $status;
                $item->save();
                $item->sendStatusUpdatedEmails();
                return redirect()->back()->with('success', __('Update success'));
            }
            return redirect()->back()->with('error', __('Booking not found!'));
        }
        return redirect()->back()->with('error', __('Update fail!'));
    }
}
